name: CI/CD

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-vesion: 16

      - name: Download deps
        run: npm i

      - name: Run tests
        run: npm run test

  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service 1ec59598-e4ec-486e-b5e9-e48de2e02ab2
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
